### ISSUE TITLE
ERDs

### ISSUE THREAD

**Issue by mh610creative** [mh610creative/Techlux#3]
Construct ERD to figure out number of tables required and relationships for 1:M and M:M

**Comment by mh610creative** [comment]
- [ ] 1:M Relationship (One product with multiple reviews)
- [ ] M:M (Multiple products and multiple reviews)
- [ ] 1:M (1 User has multiple reviews on multiple products)
- [ ] M:M (Several Users have multiple reviews on multiple products)
- [ ] What is the Join Table?

**Comment by mh610creative** [comment]
Completed ERD, pending final review

**Comment by acklins** [comment]
k sent this last night  with completed items checked, through git project
not sure if you are able to see my check marks?
[image: Screen Shot 2021-03-15 at 10.30.53 AM.png]

**Comment by mh610creative** [comment]
This is just for the DB model/ERD i made.

**Comment by mh610creative** [comment]
Completed ERD
